export const ADVANCED_OPTIONS_UNLOCKED_KEY: string = 'advancedOptionsUnlocked'
export const PLAYER_DEBUG_OPTIONS_UNLOCKED_KEY: string = 'playerDebugOptionsUnlocked'
export const PLAYER_DEBUG_OPTIONS_UNLOCK_TAP_COUNT: number = 30
export const PLAYER_DEBUG_OPTIONS_UNLOCK_WINDOW_MS: number = 60000
export const HIDE_LOCAL_PAGE_KEY: string = 'hideLocalPage'
export const HIDE_LOCAL_PAGE_DEFAULT: boolean = false
