#!/bin/bash
# build_ffmpeg_ohos.sh - Cross-compile FFmpeg (dex2oat fork with OHCodec) for HarmonyOS NEXT (aarch64)
# Run in WSL with NTFS metadata enabled
#
# Prerequisites: git, make, nasm/yasm, pkg-config
#
# Usage:
#   ./build_ffmpeg_ohos.sh [OHOS_NDK_PATH] [INSTALL_PREFIX]

set -euo pipefail

TARGET=aarch64-linux-ohos
ARCH=aarch64

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MPV_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OHOS_NDK="${1:-$HOME/ohos_ndk}"
INSTALL_PREFIX="${2:-${MPV_ROOT}/prebuilt/ffmpeg}"
JOBS=$(nproc)
FFMPEG_SRC="${MPV_ROOT}/ffmpeg-src"

BUILD_TMPDIR="${MPV_ROOT}/build/tmp"
mkdir -p "${BUILD_TMPDIR}"
export TMPDIR="${BUILD_TMPDIR}"

WRAPPER_DIR="${MPV_ROOT}/build/wrappers"
mkdir -p "${WRAPPER_DIR}"
export OHOS_NDK WRAPPER_DIR MPV_BUILD_TMPDIR="${BUILD_TMPDIR}"

wsl_to_win() {
    # Keep explicit /mnt/<drive>/ paths logical. wslpath resolves symlinks and
    # junctions back to the DevEco Studio directory, whose space breaks the
    # Windows clang command line used by the cross compiler.
    if [[ "$1" =~ ^/mnt/([a-zA-Z])/(.*)$ ]]; then
        local drive="${BASH_REMATCH[1]}"
        local rest="${BASH_REMATCH[2]}"
        drive="${drive^^}"
        rest="${rest//\\/}"
        rest="${rest//\//\\}"
        printf '%s' "${drive}:\\${rest}"
    else
        wslpath -w "$1" 2>/dev/null || echo "$1"
    fi
}

OHOS_NDK_WIN=$(wsl_to_win "${OHOS_NDK}")
SYSROOT_WIN=$(wsl_to_win "${OHOS_NDK}/sysroot")
export OHOS_NDK_WIN_OVERRIDE="${OHOS_NDK_WIN}"


CC="${OHOS_NDK}/llvm/bin/clang.exe"
AR="${WRAPPER_DIR}/ohos-ar"
NM="${WRAPPER_DIR}/ohos-nm"
RANLIB="${WRAPPER_DIR}/ohos-ranlib"
STRIP="${WRAPPER_DIR}/ohos-strip"

DEPS_DIR="${MPV_ROOT}/prebuilt/deps"

echo "=== FFmpeg (dex2oat/OHCodec) Cross-Compile for HarmonyOS NEXT ==="
echo "NDK (Win):     ${OHOS_NDK_WIN}"
echo "Sysroot (Win): ${SYSROOT_WIN}"
echo "FFmpeg src:    ${FFMPEG_SRC}"
echo "Install:       ${INSTALL_PREFIX}"
echo "Jobs:          ${JOBS}"

[ ! -d "${OHOS_NDK}" ] && { echo "ERROR: NDK not found"; exit 1; }
[ ! -f "${CC}" ] && { echo "ERROR: clang.exe not found"; exit 1; }

echo "Verifying compiler..."
"${CC}" --version | head -1

python3 "${SCRIPT_DIR}/gen_wrappers.py"
CC_WRAPPER="${WRAPPER_DIR}/ohos-clang"
CXX_WRAPPER="${WRAPPER_DIR}/ohos-clang++"

echo "Testing wrapper..."
echo 'int main(){return 0;}' > "${BUILD_TMPDIR}/toolchain_test.c"
if "${CC_WRAPPER}" -fPIC -c "${BUILD_TMPDIR}/toolchain_test.c" -o "${BUILD_TMPDIR}/toolchain_test.o" 2>&1; then
    file "${BUILD_TMPDIR}/toolchain_test.o"
    rm -f "${BUILD_TMPDIR}/toolchain_test.c" "${BUILD_TMPDIR}/toolchain_test.o"
    echo "Wrapper test PASSED"
else
    rm -f "${BUILD_TMPDIR}/toolchain_test.c" "${BUILD_TMPDIR}/toolchain_test.o"
    echo "Wrapper test FAILED"
    exit 1
fi

[ -f "${FFMPEG_SRC}/configure" ] || {
    echo "ERROR: project-owned FFmpeg source not found at ${FFMPEG_SRC}"
    exit 1
}

cd "${FFMPEG_SRC}"
# Dependency files generated by a previous Windows-side build can contain
# drive-letter paths (for example C:), which GNU make parses as extra target
# separators under WSL. They are disposable and must not survive a toolchain
# or host-path change.
find . -type f -name '*.d' -delete
make distclean 2>/dev/null || true

echo "Configuring FFmpeg (with OHCodec support)..."

bash ./configure \
    --prefix="${INSTALL_PREFIX}" \
    --enable-cross-compile \
    --cross-prefix="" \
    --cc="${CC_WRAPPER}" \
    --cxx="${CXX_WRAPPER}" \
    --ar="${AR}" \
    --nm="${NM}" \
    --ranlib="${RANLIB}" \
    --strip="${STRIP}" \
    --extra-cflags="-fPIC -O2 -flto -I${DEPS_DIR}/include" \
    --extra-ldflags="-L${DEPS_DIR}/lib" \
    --target-os=linux \
    --arch=${ARCH} \
    --enable-static \
    --disable-shared \
    --disable-programs \
    --disable-doc \
    --disable-debug \
    --disable-everything \
    --enable-protocol=file,http,https,hls,crypto,pipe,tls \
    --enable-demuxer=matroska,mov,flv,hls,mp4,ass,srt,webvtt \
    --enable-decoder=h264,hevc,aac,ac3,eac3,opus,flac,vp8,vp9,av1,ass,srt,subrip,webvtt \
    --enable-encoder=mpeg4,h264_oh,aac,opus,flac,ass,srt \
    --enable-parser=h264,hevc,aac,ac3,opus,vp9,flac \
    --enable-muxer=matroska,mp4 \
    --enable-bsf=h264_mp4toannexb,hevc_mp4toannexb,aac_adtstoasc \
    --enable-filter=aresample,scale \
    --enable-swresample \
    --enable-swscale \
    --enable-mbedtls \
    --enable-version3 \
    --disable-avdevice \
    --disable-vulkan \
    --enable-small \
    --enable-lto

echo "Enabling CONFIG_OHCODEC in config.mak..."
sed -i 's/^!CONFIG_OHCODEC=.*/CONFIG_OHCODEC=1/' ffbuild/config.mak
if ! grep -q "^CONFIG_OHCODEC=1" ffbuild/config.mak; then
    echo "CONFIG_OHCODEC=1" >> ffbuild/config.mak
fi

echo "Enabling CONFIG_OHCODEC in config.h..."
sed -i 's/#define CONFIG_OHCODEC 0/#define CONFIG_OHCODEC 1/' config.h
if ! grep -q "#define CONFIG_OHCODEC 1" config.h; then
    echo "#define CONFIG_OHCODEC 1" >> config.h
fi

echo "Enabling OHCodec decoders (h264_oh, hevc_oh) in config.mak..."
sed -i 's/^!CONFIG_H264_OH_DECODER=.*/CONFIG_H264_OH_DECODER=1/' ffbuild/config.mak
if ! grep -q "^CONFIG_H264_OH_DECODER=1" ffbuild/config.mak; then
    echo "CONFIG_H264_OH_DECODER=1" >> ffbuild/config.mak
fi
sed -i 's/^!CONFIG_HEVC_OH_DECODER=.*/CONFIG_HEVC_OH_DECODER=1/' ffbuild/config.mak
if ! grep -q "^CONFIG_HEVC_OH_DECODER=1" ffbuild/config.mak; then
    echo "CONFIG_HEVC_OH_DECODER=1" >> ffbuild/config.mak
fi

echo "Enabling OHCodec H.264 encoder in config.mak..."
sed -i 's/^!CONFIG_H264_OH_ENCODER=.*/CONFIG_H264_OH_ENCODER=1/' ffbuild/config.mak
if ! grep -q "^CONFIG_H264_OH_ENCODER=1" ffbuild/config.mak; then
    echo "CONFIG_H264_OH_ENCODER=1" >> ffbuild/config.mak
fi

echo "Enabling OHCodec decoders in config.h..."
for dec in CONFIG_H264_OH_DECODER CONFIG_HEVC_OH_DECODER; do
    if grep -q "#define ${dec} " config.h; then
        sed -i "s/#define ${dec} 0/#define ${dec} 1/" config.h
    else
        echo "#define ${dec} 1" >> config.h
    fi
done

if grep -q "#define CONFIG_H264_OH_ENCODER " config.h; then
    sed -i 's/#define CONFIG_H264_OH_ENCODER 0/#define CONFIG_H264_OH_ENCODER 1/' config.h
else
    echo "#define CONFIG_H264_OH_ENCODER 1" >> config.h
fi

echo "Adding OHCodec decoders to codec_list.c (using python)..."
python3 -c "
import re
with open('libavcodec/codec_list.c', 'r') as f:
    content = f.read()
if 'ff_h264_oh_decoder' not in content:
    content = content.replace('&ff_h264_decoder,', '&ff_h264_decoder,\n    &ff_h264_oh_decoder,')
if 'ff_hevc_oh_decoder' not in content:
    content = content.replace('&ff_hevc_decoder,', '&ff_hevc_decoder,\n    &ff_hevc_oh_decoder,')
if 'ff_h264_oh_encoder' not in content:
    content = content.replace('&ff_mpeg4_encoder,', '&ff_mpeg4_encoder,\n    &ff_h264_oh_encoder,')
with open('libavcodec/codec_list.c', 'w') as f:
    f.write(content)
"

# allcodecs.c includes codec_list.c, but the generated dependency file can be
# stale after copying this native tree. Force it to be compiled again so newly
# enabled decoders (including AC3/EAC3) are present in the registry.
rm -f libavcodec/allcodecs.o

echo "Adding OHCodec decoders to config_components.h..."
for dec in CONFIG_H264_OH_DECODER CONFIG_HEVC_OH_DECODER; do
    if [ -f config_components.h ]; then
        if grep -q "#define ${dec} " config_components.h; then
            sed -i "s/#define ${dec} 0/#define ${dec} 1/" config_components.h
        else
            echo "#define ${dec} 1" >> config_components.h
        fi
    fi
done
if [ -f config_components.h ]; then
    if grep -q "#define CONFIG_H264_OH_ENCODER " config_components.h; then
        sed -i 's/#define CONFIG_H264_OH_ENCODER 0/#define CONFIG_H264_OH_ENCODER 1/' config_components.h
    else
        echo "#define CONFIG_H264_OH_ENCODER 1" >> config_components.h
    fi
fi

echo "Building FFmpeg (10-30 min)..."
make -j${JOBS}

echo "Manually compiling hwcontext_oh.o and adding to libavutil.a..."
"${CC_WRAPPER}" -fPIC -O2 -flto -c -I. -Ilibavutil -o libavutil/hwcontext_oh.o libavutil/hwcontext_oh.c
"${AR}" rcs libavutil/libavutil.a libavutil/hwcontext_oh.o

echo "Manually compiling ohcodec.o, ohdec.o and ohenc.o and adding to libavcodec.a..."
"${CC_WRAPPER}" -fPIC -O2 -c -I. -Ilibavcodec -Ilibavutil -o libavcodec/ohcodec.o libavcodec/ohcodec.c
"${CC_WRAPPER}" -fPIC -O2 -c -I. -Ilibavcodec -Ilibavutil -o libavcodec/ohdec.o libavcodec/ohdec.c
"${CC_WRAPPER}" -fPIC -O2 -c -I. -Ilibavcodec -Ilibavutil -o libavcodec/ohenc.o libavcodec/ohenc.c
"${AR}" rcs libavcodec/libavcodec.a libavcodec/ohcodec.o libavcodec/ohdec.o libavcodec/ohenc.o

echo "Installing FFmpeg (manual copy)..."
mkdir -p "${INSTALL_PREFIX}/lib" "${INSTALL_PREFIX}/include"
for lib in libavutil libswresample libswscale libavcodec libavformat libavfilter; do
    if [ -f "${FFMPEG_SRC}/${lib}/${lib}.a" ]; then
        cp -v "${FFMPEG_SRC}/${lib}/${lib}.a" "${INSTALL_PREFIX}/lib/"
    fi
done
cp -rv "${FFMPEG_SRC}/ffbuild/config.sh" "${INSTALL_PREFIX}/" 2>/dev/null || true
for dir in libavutil libswresample libswscale libavcodec libavformat libavfilter; do
    if [ -d "${FFMPEG_SRC}/${dir}/" ]; then
        mkdir -p "${INSTALL_PREFIX}/include/${dir}"
        for h in "${FFMPEG_SRC}/${dir}/"*.h; do
            [ -f "$h" ] && cp -v "$h" "${INSTALL_PREFIX}/include/${dir}/"
        done
    fi
done
if [ -d "${FFMPEG_SRC}/compat/atomics/gcc/" ]; then
    mkdir -p "${INSTALL_PREFIX}/include/compat/atomics/gcc"
    cp -v "${FFMPEG_SRC}/compat/atomics/gcc/stdatomic.h" "${INSTALL_PREFIX}/include/compat/atomics/gcc/" 2>/dev/null || true
fi

echo "Verifying installed libraries..."
ls -la "${INSTALL_PREFIX}/lib/"

echo "=== FFmpeg build complete ==="
